#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x03,0x44,0x22,0xc4,0x24,0x75,
};

static const uint8_t chainparams_seed_test[] = {
     0x01,0x04,0xd9,0x48,0x04,0x9d,0x4b,0x87,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
